[package]
name = "inventario"
version = "1.0.0"
description = "Aplicación de escritorio de Inventario"
authors = ["Inventario"]
edition = "2021"

[lib]
name = "inventario_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
