import { Check, Edit3, Plus, Power, WalletCards } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { apiRequest } from "../api/client.js";
import { Alert } from "../components/Alert.jsx";
import { Button } from "../components/Button.jsx";
import { Card } from "../components/Card.jsx";
import { EmptyState } from "../components/EmptyState.jsx";
import { Input } from "../components/Input.jsx";
import { PageHeader } from "../components/PageHeader.jsx";
import { Select } from "../components/Select.jsx";
import { Spinner } from "../components/Spinner.jsx";
import { useAuth } from "../context/AuthContext.jsx";
import { HelpInfoPanel } from "../components/HelpInfoPanel.jsx";

const typeLabels = { fixed: "Fijo", variable: "Variable" };
const categoryLabels = { labor: "Mano de obra", logistics: "Logística", rent: "Renta", utilities: "Servicios", supplies: "Insumos", maintenance: "Mantenimiento", marketing: "Marketing", software: "Software", commissions: "Comisiones", taxes: "Impuestos", banking: "Bancos", other: "Otros", custom: "Personalizada" };
const categoryOptions = Object.entries(categoryLabels);
const frequencyLabels = { weekly: "Semanal", monthly: "Mensual", yearly: "Anual", one_time: "Único" };
const today = () => new Date().toISOString().slice(0, 10);
const emptyForm = () => ({ name: "", description: "", category: "labor", customCategoryName: "", amount: "", costType: "fixed", frequency: "monthly", startDate: today(), endDate: "", notes: "" });
const money = (value, currency) => new Intl.NumberFormat("es-MX", { style: "currency", currency }).format(Number(value));
const monthlyEquivalent = (cost) => cost.frequency === "weekly" ? Number(cost.amount) * 52 / 12 : cost.frequency === "yearly" ? Number(cost.amount) / 12 : cost.frequency === "one_time" ? 0 : Number(cost.amount);
const fieldsByName = (fields = []) => Object.fromEntries(fields.map((field) => [field.field, field.message]));

export function BusinessCostsPage() {
  const { session } = useAuth();
  const canManage = ["owner", "manager"].includes(session.membership?.role);
  const currency = session.activeBusiness?.currency ?? "MXN";
  const [costs, setCosts] = useState([]); const [form, setForm] = useState(emptyForm); const [editingId, setEditingId] = useState(null); const [categoryFilter, setCategoryFilter] = useState("all");
  const [isFormOpen, setIsFormOpen] = useState(false); const [errors, setErrors] = useState({}); const [requestError, setRequestError] = useState(""); const [notice, setNotice] = useState(""); const [isLoading, setIsLoading] = useState(true); const [isSaving, setIsSaving] = useState(false);
  const loadCosts = useCallback(async () => { setIsLoading(true); setRequestError(""); try { const result = await apiRequest("/business-costs"); setCosts(result.costs ?? []); } catch (error) { setRequestError(error.message || "No fue posible cargar los gastos."); } finally { setIsLoading(false); } }, []);
  useEffect(() => { loadCosts(); }, [loadCosts]);
  function openNew(category = "labor") { setEditingId(null); setForm({ ...emptyForm(), category }); setErrors({}); setRequestError(""); setNotice(""); setIsFormOpen(true); }
  function openEdit(cost) { setEditingId(cost.id); setForm({ ...emptyForm(), name: cost.name, description: cost.description ?? "", category: cost.category ?? "labor", customCategoryName: cost.customCategoryName ?? "", amount: String(cost.amount), costType: cost.costType, frequency: cost.frequency, startDate: cost.startDate?.slice(0, 10) ?? today(), endDate: cost.endDate?.slice(0, 10) ?? "", notes: cost.notes ?? "" }); setErrors({}); setRequestError(""); setIsFormOpen(true); }
  function updateField(name, value) { setForm((current) => ({ ...current, [name]: value })); setErrors((current) => ({ ...current, [name]: undefined })); setRequestError(""); }
  async function submit(event) { event.preventDefault(); const nextErrors = {}; if (!form.name.trim()) nextErrors.name = "El concepto es obligatorio."; if (form.category === "custom" && !form.customCategoryName?.trim()) nextErrors.customCategoryName = "Escribe el nombre de la categoría."; if (!Number.isFinite(Number(form.amount)) || Number(form.amount) <= 0) nextErrors.amount = "El importe debe ser mayor que cero."; if (form.endDate && form.endDate < form.startDate) nextErrors.endDate = "La fecha de fin debe ser posterior a la fecha de inicio."; if (Object.keys(nextErrors).length) { setErrors(nextErrors); return; } setIsSaving(true); setErrors({}); setRequestError(""); try { const result = await apiRequest(editingId ? `/business-costs/${editingId}` : "/business-costs", { method: editingId ? "PUT" : "POST", body: { ...form, customCategoryName: form.category === "custom" ? form.customCategoryName : "", amount: Number(form.amount) }, csrf: true }); setCosts((current) => editingId ? current.map((cost) => cost.id === editingId ? result.cost : cost) : [...current, result.cost]); setIsFormOpen(false); setNotice(editingId ? "Gasto actualizado correctamente." : "Gasto creado correctamente."); } catch (error) { if (error.code === "VALIDATION_ERROR") setErrors(fieldsByName(error.fields)); setRequestError(error.message || "No fue posible guardar el gasto."); } finally { setIsSaving(false); } }
  async function toggleCost(cost) { try { const result = await apiRequest(`/business-costs/${cost.id}/status`, { method: "PATCH", body: { isActive: !cost.isActive }, csrf: true }); setCosts((current) => current.map((item) => item.id === cost.id ? result.cost : item)); setNotice(result.cost.isActive ? "Gasto activado." : "Gasto desactivado."); } catch (error) { setRequestError(error.message || "No fue posible cambiar el estado del gasto."); } }
  if (isLoading) return <section className="dashboard-state"><Spinner label="Cargando gastos" /></section>;
  if (requestError && costs.length === 0 && !isFormOpen) return <Alert><div className="dashboard-error"><span>{requestError}</span><Button variant="secondary" onClick={loadCosts}>Reintentar</Button></div></Alert>;
  const active = costs.filter((cost) => cost.isActive); const total = (predicate) => active.filter(predicate).reduce((sum, cost) => sum + monthlyEquivalent(cost), 0); const totals = { fixed: total((cost) => cost.costType === "fixed"), variable: total((cost) => cost.costType === "variable") }; const visibleCosts = costs.filter((cost) => categoryFilter === "all" || (cost.category ?? "labor") === categoryFilter); const categoryTotals = categoryOptions.map(([key, label]) => ({ key, label, value: total((cost) => (cost.category ?? "labor") === key) })).filter((item) => item.value > 0 || costs.some((cost) => (cost.category ?? "labor") === item.key));
  return <section className="business-costs-page"><PageHeader title="Costos" description="Define gastos del negocio para el resumen financiero y el punto de equilibrio." /><HelpInfoPanel moduleKey="costs" businessId={session.activeBusiness?.id} />
    {requestError && <Alert>{requestError}</Alert>}{notice && <div className="business-costs-notice" role="status"><Check aria-hidden="true" />{notice}</div>}<div className="business-costs-totals">{[["Total fijo mensual", totals.fixed], ["Total variable", totals.variable]].map(([label, value]) => <Card key={label}><span>{label}</span><strong>{money(value, currency)}</strong></Card>)}{categoryTotals.map((item) => <Card key={item.key}><span>Total {item.label.toLowerCase()}</span><strong>{money(item.value, currency)}</strong></Card>)}</div>
    <Card className="business-cost-filter"><Select id="business-cost-filter" label="Filtrar por categoría" value={categoryFilter} onChange={(event) => setCategoryFilter(event.target.value)}><option value="all">Todas las categorías</option>{categoryOptions.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</Select></Card>
    {isFormOpen && canManage && <Card className="business-cost-form"><h2>{editingId ? "Editar gasto" : "Nuevo gasto"}</h2><form className="business-cost-form__fields" onSubmit={submit} noValidate><Input id="business-cost-name" label="Concepto *" value={form.name} onChange={(event) => updateField("name", event.target.value)} maxLength="150" required error={errors.name} /><Select id="business-cost-category" label="Categoría" value={form.category} onChange={(event) => updateField("category", event.target.value)}>{categoryOptions.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</Select>{form.category === "custom" && <Input id="business-cost-custom-category" label="Nombre de categoría *" value={form.customCategoryName} onChange={(event) => updateField("customCategoryName", event.target.value)} maxLength="100" required error={errors.customCategoryName} />}<Input id="business-cost-description" label="Descripción" value={form.description} onChange={(event) => updateField("description", event.target.value)} maxLength="500" /><Input id="business-cost-amount" label={`Monto * (${currency})`} type="number" min="0.01" step="0.01" value={form.amount} onChange={(event) => updateField("amount", event.target.value)} required error={errors.amount} /><Select id="business-cost-type" label="Tipo" value={form.costType} onChange={(event) => updateField("costType", event.target.value)}><option value="fixed">Fijo</option><option value="variable">Variable</option></Select><Select id="business-cost-frequency" label="Periodicidad" value={form.frequency} onChange={(event) => updateField("frequency", event.target.value)}><option value="weekly">Semanal</option><option value="monthly">Mensual</option><option value="one_time">Único</option><option value="yearly">Anual</option></Select><Input id="business-cost-start-date" label="Fecha de inicio" type="date" value={form.startDate} onChange={(event) => updateField("startDate", event.target.value)} /><Input id="business-cost-end-date" label="Fecha de fin" type="date" value={form.endDate} onChange={(event) => updateField("endDate", event.target.value)} error={errors.endDate} /><Input id="business-cost-notes" label="Notas" value={form.notes} onChange={(event) => updateField("notes", event.target.value)} maxLength="1000" /><div className="business-cost-form__actions"><Button type="button" variant="secondary" onClick={() => setIsFormOpen(false)}>Cancelar</Button><Button type="submit" disabled={isSaving}>{isSaving ? "Guardando…" : "Guardar gasto"}</Button></div></form></Card>}
    {visibleCosts.length === 0 ? <EmptyState title="Sin gastos en esta categoría" description="Agrega un gasto para comenzar a administrarlo." action={canManage && <Button onClick={() => openNew(categoryFilter === "all" ? "labor" : categoryFilter)}><Plus aria-hidden="true" />Agregar gasto</Button>} /> : <Card className="business-costs-table-card"><div className="business-costs-table-wrap"><table className="business-costs-table"><thead><tr><th>Concepto</th><th>Categoría</th><th>Monto</th><th>Tipo</th><th>Periodicidad</th><th>Estado</th><th>Vigencia</th>{canManage && <th>Acciones</th>}</tr></thead><tbody>{visibleCosts.map((cost) => <tr key={cost.id} className={!cost.isActive ? "business-costs-row--inactive" : ""}><th scope="row">{cost.name}</th><td>{cost.category === "custom" ? cost.customCategoryName : categoryLabels[cost.category ?? "labor"]}</td><td>{money(cost.amount, currency)}</td><td>{typeLabels[cost.costType] ?? cost.costType}</td><td>{frequencyLabels[cost.frequency] ?? cost.frequency}</td><td><span className={`business-cost-status business-cost-status--${cost.isActive ? "active" : "inactive"}`}>{cost.isActive ? "Activo" : "Inactivo"}</span></td><td>{cost.startDate?.slice(0, 10) ?? "—"}{cost.endDate ? ` — ${cost.endDate.slice(0, 10)}` : ""}</td>{canManage && <td><div className="business-costs-actions"><Button variant="secondary" onClick={() => openEdit(cost)} disabled={!cost.isActive}><Edit3 aria-hidden="true" />Editar</Button><Button variant={cost.isActive ? "danger" : "secondary"} onClick={() => toggleCost(cost)}><Power aria-hidden="true" />{cost.isActive ? "Desactivar" : "Activar"}</Button></div></td>}</tr>)}</tbody></table></div></Card>}
    {!canManage && <p className="business-costs-readonly"><WalletCards aria-hidden="true" />Tienes acceso de consulta. Solo owner y manager pueden modificar gastos.</p>}</section>;
}
