import { matchedData, validationResult } from "express-validator";
import * as q from "../db/customerCollectionsQueries.js";
import { accountTotals, chargeState } from "../services/customerCollectionsService.js";

function id(value) { const n=Number(value); return Number.isSafeInteger(n)&&n>0?n:null; }
function validation(res) { const e=validationResult(res.req); if(e.isEmpty()) return null; return res.status(400).json({ error:{ code:"VALIDATION_ERROR", message:"Revisa los campos enviados.", fields:e.array().map(x=>({field:x.path,message:x.msg})) } }); }
function customer(x) { return { id:Number(x.id),name:x.name,phone:x.phone,email:x.email,address:x.address,notes:x.notes,status:x.status,balance:Number(x.balance||0),createdAt:x.created_at,updatedAt:x.updated_at }; }
function charge(x) { return { id:Number(x.id),customerId:Number(x.customer_id),concept:x.concept,amount:Number(x.amount),paid:Number(x.paid||0),balance:Math.max(0,Number(x.amount)-Number(x.paid||0)),frequency:x.frequency,dueDate:x.due_date,status:chargeState({amount:x.amount,paid:x.paid||0,dueDate:x.due_date,status:x.status}),notes:x.notes }; }
function payment(x) { return { id:Number(x.id),customerId:Number(x.customer_id),chargeId:x.charge_id===null?null:Number(x.charge_id),folio:x.folio,amount:Number(x.amount),paymentMethod:x.payment_method,paidAt:x.paid_at,previousBalance:Number(x.previous_balance),remainingBalance:Number(x.remaining_balance),status:x.status,customerName:x.customer_name,concept:x.concept,createdByUsername:x.created_by_username }; }
export async function listCustomers(req,res,next){try{return res.json({data:{customers:(await q.listCustomers(req.business.id,typeof req.query.q==="string"?req.query.q.trim():"")).map(customer)}})}catch(e){next(e)}}
export async function getCustomer(req,res,next){try{const x=await q.getCustomer(req.business.id,id(req.params.customerId));if(!x)return res.status(404).json({error:{code:"CUSTOMER_NOT_FOUND",message:"Cliente no encontrado."}});return res.json({data:{customer:customer(x)}})}catch(e){next(e)}}
export async function createCustomer(req,res,next){const e=validation(res);if(e)return e;try{return res.status(201).json({data:{customer:customer(await q.createCustomer({...matchedData(req),businessId:req.business.id,createdBy:req.session.user.id}))}})}catch(e){next(e)}}
export async function updateCustomer(req,res,next){const e=validation(res);if(e)return e;try{const x=await q.updateCustomer({...matchedData(req),businessId:req.business.id,id:id(req.params.customerId)});if(!x)return res.status(404).json({error:{code:"CUSTOMER_NOT_FOUND",message:"Cliente no encontrado."}});return res.json({data:{customer:customer(x)}})}catch(e){next(e)}}
export async function setCustomerStatus(req,res,next){const e=validation(res);if(e)return e;try{const x=await q.setCustomerStatus(req.business.id,id(req.params.customerId),matchedData(req).status);if(!x)return res.status(404).json({error:{code:"CUSTOMER_NOT_FOUND",message:"Cliente no encontrado."}});return res.json({data:{customer:customer(x)}})}catch(e){next(e)}}
export async function listCharges(req,res,next){try{return res.json({data:{charges:(await q.listCharges(req.business.id,id(req.query.customerId))).map(charge)}})}catch(e){next(e)}}
export async function createCharge(req,res,next){const e=validation(res);if(e)return e;try{return res.status(201).json({data:{charge:charge(await q.createCharge({...matchedData(req),businessId:req.business.id,createdBy:req.session.user.id}))}})}catch(e){next(e)}}
export async function getCharge(req,res,next){try{const x=await q.getCharge(req.business.id,id(req.params.chargeId));if(!x)return res.status(404).json({error:{code:"CHARGE_NOT_FOUND",message:"Cargo no encontrado."}});return res.json({data:{charge:charge(x)}})}catch(e){next(e)}}
export async function updateCharge(req,res,next){const e=validation(res);if(e)return e;try{const x=await q.updateCharge({...matchedData(req),businessId:req.business.id,id:id(req.params.chargeId)});if(!x)return res.status(404).json({error:{code:"CHARGE_NOT_FOUND",message:"Cargo no encontrado."}});return res.json({data:{charge:charge(x)}})}catch(e){next(e)}}
export async function updateChargeStatus(req,res,next){const e=validation(res);if(e)return e;try{const x=await q.updateChargeStatus(req.business.id,id(req.params.chargeId),matchedData(req).status);if(!x)return res.status(404).json({error:{code:"CHARGE_NOT_FOUND",message:"Cargo no encontrado."}});return res.json({data:{charge:charge(x)}})}catch(e){next(e)}}
export async function listPayments(req,res,next){try{return res.json({data:{payments:(await q.listPayments(req.business.id,id(req.query.customerId))).map(payment)}})}catch(e){next(e)}}
export async function getPayment(req,res,next){try{const x=await q.getPayment(req.business.id,id(req.params.paymentId));if(!x)return res.status(404).json({error:{code:"PAYMENT_NOT_FOUND",message:"Pago no encontrado."}});return res.json({data:{payment:payment(x)}})}catch(e){next(e)}}
export async function createPayment(req,res,next){const e=validation(res);if(e)return e;try{return res.status(201).json({data:{payment:payment(await q.createPayment({...matchedData(req),businessId:req.business.id,createdBy:req.session.user.id}))}})}catch(e){next(e)}}
export async function cancelPayment(req,res,next){const e=validation(res);if(e)return e;try{const x=await q.cancelPayment({businessId:req.business.id,id:id(req.params.paymentId),userId:req.session.user.id,reason:matchedData(req).cancellationReason});if(!x)return res.status(404).json({error:{code:"PAYMENT_NOT_FOUND",message:"Pago no encontrado o ya cancelado."}});return res.json({data:{payment:payment(x)}})}catch(e){next(e)}}
export async function accountStatement(req,res,next){try{const customerId=id(req.params.customerId);const [charges,payments]=await Promise.all([q.listCharges(req.business.id,customerId),q.listPayments(req.business.id,customerId)]);return res.json({data:{customerId,charges:charges.map(charge),payments:payments.map(payment),totals:accountTotals(charges,payments)}})}catch(e){next(e)}}
export async function balance(req,res,next){try{const [charges,payments]=await Promise.all([q.listCharges(req.business.id,id(req.params.customerId)),q.listPayments(req.business.id,id(req.params.customerId))]);return res.json({data:accountTotals(charges,payments)})}catch(e){next(e)}}
export async function collectionsSummary(req,res,next){try{const x=await q.summary(req.business.id);return res.json({data:{totalCharges:Number(x.total_charges),totalPaid:Number(x.paid_total),balance:Math.max(0,Number(x.total_charges)-Number(x.paid_total)),activeCustomers:Number(x.active_customers),overdueAccounts:Number(x.overdue_accounts),period:req.query.period==="month"?"month":"week"}})}catch(e){next(e)}}
export async function receipt(req,res,next){try{const x=await q.getPayment(req.business.id,id(req.params.paymentId));if(!x)return res.status(404).json({error:{code:"PAYMENT_NOT_FOUND",message:"Pago no encontrado."}});return res.json({data:{receipt:payment(x)}})}catch(e){next(e)}}
export async function collectionAlerts(req,res,next){try{const today=new Date().toISOString().slice(0,10);const alerts=(await q.listCollectionAlerts(req.business.id)).map((x)=>{const days=Number(x.days_until_due);const overdue=days<0;return {id:`monthly-${x.charge_id}-${today}`,chargeId:Number(x.charge_id),customerId:Number(x.customer_id),customerName:x.customer_name,concept:x.concept,originalAmount:Number(x.amount),paidAmount:Number(x.paid),remainingBalance:Number(x.amount)-Number(x.paid),dueDate:x.due_date instanceof Date ? x.due_date.toISOString().slice(0,10) : x.due_date,status:overdue?"overdue":"upcoming",message:overdue?"Pago mensual vencido":"Pago mensual próximo a vencer"};});return res.json({data:{alerts}})}catch(e){next(e)}}
