import { matchedData, validationResult } from "express-validator";
import { cancelReturn, createReturn, getReturn, listReturns } from "../db/inventoryReturnQueries.js";
const types={supplier_return:"Devolución a proveedor",damage:"Mercancía dañada",loss:"Pérdida",destroyed:"Destrucción",expired:"Caducidad"};
const id=(value)=>/^[1-9]\d*$/.test(String(value))?Number(value):null;
function invalid(res,fields){return res.status(400).json({error:{code:"VALIDATION_ERROR",message:"Revisa los campos enviados.",fields}})}
function validation(req,res){const result=validationResult(req);return result.isEmpty()?null:invalid(res,result.array().map(e=>({field:e.path,message:e.msg})))}
export async function listReturnsController(req,res,next){try{const page=Math.max(1,Number(req.query.page)||1),returnType=types[req.query.type]?req.query.type:"",status=["draft","registered","cancelled"].includes(req.query.status)?req.query.status:"",q=typeof req.query.q==="string"?req.query.q.trim().slice(0,100):"";const result=await listReturns({businessId:req.business.id,returnType,status,q,limit:20,offset:(page-1)*20});const totalPages=Math.max(1,Math.ceil(result.count/20));return res.json({data:{returns:result.rows,filters:{type:returnType,status,q},pagination:{page:Math.min(page,totalPages),pageSize:20,totalItems:result.count,totalPages}}})}catch(e){next(e)}}
export async function getReturnController(req,res,next){const returnId=id(req.params.returnId);if(!returnId)return invalid(res,[{field:"returnId",message:"La devolución no es válida."}]);try{const result=await getReturn(req.business.id,returnId);if(!result)return res.status(404).json({error:{code:"RETURN_NOT_FOUND",message:"No se encontró la devolución."}});return res.json({data:result})}catch(e){next(e)}}
export async function createReturnController(req,res,next){const bad=validation(req,res);if(bad)return bad;try{const result=await createReturn({businessId:req.business.id,userId:req.session.user.id,data:matchedData(req)});const messages={order_not_found:"La orden no está recibida o no pertenece al negocio.",location_mismatch:"La ubicación no coincide con la orden.",item_not_received:"El producto no fue recibido en la orden.",return_exceeds_received:"La devolución supera la cantidad recibida pendiente.",insufficient_stock:"No hay stock suficiente en la ubicación.",product_not_found:"El producto no pertenece al negocio o está archivado."};if(result.error)return res.status(result.error==="order_not_found"?404:422).json({error:{code:result.error.toUpperCase(),message:messages[result.error]||"No se pudo registrar la devolución."}});return res.status(201).json({data:{...result,id:result.return.id}})}catch(e){next(e)}}
export async function cancelReturnController(req,res,next){const returnId=id(req.params.returnId);if(!returnId)return invalid(res,[{field:"returnId",message:"La devolución no es válida."}]);try{const result=await cancelReturn(req.business.id,returnId,req.session.user.id);if(result.error)return res.status(409).json({error:{code:"RETURN_NOT_CANCELLABLE",message:"La devolución no puede cancelarse."}});return res.json({data:result})}catch(e){next(e)}}
