import ExcelJS from "exceljs";
import { inventoryCenterOptions, inventoryCenterReport } from "../db/inventoryCenterQueries.js";
import { createCsv } from "../utils/csv.js";

const id = (value) => /^[1-9]\d*$/.test(String(value)) ? Number(value) : null;
const validDate = (value) => !value || /^\d{4}-\d{2}-\d{2}$/.test(value);
const types = new Set(["entry", "exit", "adjustment", "transfer", "sale", "production"]);
function params(req, res) { const p = { q: typeof req.query.q === "string" ? req.query.q.trim().slice(0, 100) : "", productId: id(req.query.productId), categoryId: id(req.query.categoryId), locationId: id(req.query.locationId), userId: id(req.query.userId), type: types.has(req.query.type) ? req.query.type : "", dateFrom: req.query.dateFrom || "", dateTo: req.query.dateTo || "", supplier: typeof req.query.supplier === "string" ? req.query.supplier.trim().slice(0, 100) : "" }; const fields = []; if (req.query.type && !p.type) fields.push({ field: "type", message: "El tipo no es válido." }); if (!validDate(p.dateFrom) || !validDate(p.dateTo) || p.dateFrom && p.dateTo && p.dateFrom > p.dateTo) fields.push({ field: "dateFrom", message: "El rango de fechas no es válido." }); if (fields.length) { res.status(400).json({ error: { code: "VALIDATION_ERROR", message: "Revisa los filtros enviados.", fields } }); return null; } return p; }
function movementType(row) { return row.reference?.startsWith("SALE-") ? "sale" : row.reference?.startsWith("RECIPE-") ? "production" : ["transfer_in", "transfer_out"].includes(row.movement_type) ? "transfer" : row.movement_type === "opening_balance" ? "entry" : row.movement_type; }
function response(report, options, page, limit, p) { return { data: { inventory: report.inventory.map((r) => ({ product: r.name, sku: r.sku, category: r.category_name, location: r.location_name, stock: Number(r.stock), unitCost: Number(r.cost_price), totalValue: Number(r.total_value), stockStatus: r.stock_status, minimumStock: Number(r.minimum_stock) })), movements: report.movements.map((r) => ({ id: Number(r.id), date: r.created_at, type: movementType(r), reference: r.reference, product: r.item_name, sku: r.sku, category: r.category_name, quantity: Number(r.quantity_delta), location: r.location_name, user: r.username, cost: r.cost === null ? null : Number(r.cost), reason: r.reason })), withoutMovement: report.withoutMovement, lowStock: report.lowStock, options, pagination: { page, pageSize: limit, totalItems: report.movementCount, totalPages: Math.ceil(report.movementCount / limit) }, filters: p } }; }
export async function inventoryCenterApi(req, res, next) { const p = params(req, res); if (!p) return; const limit = 25; const requested = id(req.query.page) || 1; try { const [report, options] = await Promise.all([inventoryCenterReport({ businessId: req.business.id, ...p, limit, offset: (requested - 1) * limit }), inventoryCenterOptions(req.business.id)]); return res.json(response(report, options, requested, limit, p)); } catch (error) { return next(error); } }
export async function inventoryCenterCsvApi(req, res, next) { const p = params(req, res); if (!p) return; try { const report = await inventoryCenterReport({ businessId: req.business.id, ...p, limit: 100000, offset: 0 }); const rows = report.inventory.map((r) => [r.name, r.sku, r.category_name, r.location_name, Number(r.stock), Number(r.cost_price), Number(r.total_value), r.stock_status]); res.set("Content-Type", "text/csv; charset=utf-8").set("Content-Disposition", `attachment; filename="reporte-inventario-${new Date().toISOString().slice(0,10)}.csv"`); return res.send(createCsv(["Producto","SKU","Categoría","Ubicación","Existencias","Costo unitario","Valor total","Estado"], rows)); } catch (error) { return next(error); } }
export async function inventoryCenterExcelApi(req, res, next) { const p = params(req, res); if (!p) return; try { const report = await inventoryCenterReport({ businessId: req.business.id, ...p, limit: 100000, offset: 0 }); const workbook = new ExcelJS.Workbook(); const sheet = workbook.addWorksheet("Inventario actual"); sheet.columns = [{ header: "Producto", key: "product" }, { header: "SKU", key: "sku" }, { header: "Categoría", key: "category" }, { header: "Ubicación", key: "location" }, { header: "Existencias", key: "stock" }, { header: "Costo unitario", key: "unitCost" }, { header: "Valor total", key: "totalValue" }, { header: "Estado", key: "status" }]; report.inventory.forEach((r) => sheet.addRow({ product: r.name, sku: r.sku, category: r.category_name, location: r.location_name, stock: Number(r.stock), unitCost: Number(r.cost_price), totalValue: Number(r.total_value), status: r.stock_status })); sheet.getColumn("unitCost").numFmt = '"$"#,##0.00'; sheet.getColumn("totalValue").numFmt = '"$"#,##0.00'; const buffer = await workbook.xlsx.writeBuffer(); res.set("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet").set("Content-Disposition", `attachment; filename="reporte-inventario-${new Date().toISOString().slice(0,10)}.xlsx"`); return res.send(Buffer.from(buffer)); } catch (error) { return next(error); } }
