import { matchedData, validationResult } from "express-validator";
import { cancelPurchase, createPurchase, getPurchase, getPurchaseOptions, listPurchases, receivePurchase, updatePurchase } from "../db/purchaseQueries.js";

const pageSize = 20;
const id = (value) => /^[1-9]\d*$/.test(String(value)) ? Number(value) : null;
function invalid(res, errors) { return res.status(400).json({ error: { code: "VALIDATION_ERROR", message: "Revisa los campos enviados.", fields: errors } }); }
function errors(req, res) { const result = validationResult(req); return result.isEmpty() ? null : invalid(res, result.array().map((e) => ({ field: e.path, message: e.msg }))); }
function domain(res, code, message, status = 409) { return res.status(status).json({ error: { code, message } }); }

export async function purchaseOptions(req, res, next) { try { return res.json({ data: await getPurchaseOptions(req.business.id) }); } catch (error) { return next(error); } }
export async function listPurchasesController(req, res, next) { try { const pageRequested = Number.isInteger(Number(req.query.page)) && Number(req.query.page) > 0 ? Number(req.query.page) : 1; const status = typeof req.query.status === "string" && ["draft","pending","partially_received","received","cancelled"].includes(req.query.status) ? req.query.status : ""; const q = typeof req.query.q === "string" ? req.query.q.trim().slice(0, 100) : ""; const result = await listPurchases({ businessId: req.business.id, status, q, limit: pageSize, offset: (pageRequested - 1) * pageSize }); const totalPages = Math.max(1, Math.ceil(result.count / pageSize)); const page = Math.min(pageRequested, totalPages); return res.json({ data: { purchases: result.rows, filters: { status, q }, pagination: { page, pageSize, totalItems: result.count, totalPages } } }); } catch (error) { return next(error); } }
export async function getPurchaseController(req, res, next) { const purchaseId=id(req.params.purchaseId); if(!purchaseId)return invalid(res,[{field:"purchaseId",message:"La orden no es válida."}]); try { const purchase=await getPurchase(req.business.id,purchaseId); if(!purchase)return res.status(404).json({error:{code:"PURCHASE_NOT_FOUND",message:"No se encontró la orden de compra."}}); return res.json({data:purchase}); }catch(error){return next(error)} }
export async function createPurchaseController(req,res,next){const bad=errors(req,res);if(bad)return bad;try{const result=await createPurchase({businessId:req.business.id,userId:req.session.user.id,data:matchedData(req)});if(result.error)return domain(res,result.error.toUpperCase(),result.error==="supplier_not_found"?"El proveedor no pertenece al negocio activo.":"Uno de los productos no pertenece al negocio activo.",422);return res.status(201).json({data:result});}catch(error){return next(error)}}
export async function updatePurchaseController(req,res,next){const purchaseId=id(req.params.purchaseId);if(!purchaseId)return invalid(res,[{field:"purchaseId",message:"La orden no es válida."}]);const bad=errors(req,res);if(bad)return bad;try{const result=await updatePurchase({businessId:req.business.id,userId:req.session.user.id,purchaseId,data:matchedData(req)});if(result.error==="not_found")return res.status(404).json({error:{code:"PURCHASE_NOT_FOUND",message:"No se encontró la orden de compra."}});if(result.error==="not_editable")return domain(res,"PURCHASE_NOT_EDITABLE","Solo se pueden editar órdenes borrador o pendientes.");if(result.error)return domain(res,"PURCHASE_SCOPE_ERROR","El proveedor, ubicación o producto no pertenece al negocio activo.",422);return res.json({data:result});}catch(error){return next(error)}}
export async function receivePurchaseController(req,res,next){const purchaseId=id(req.params.purchaseId);if(!purchaseId)return invalid(res,[{field:"purchaseId",message:"La orden no es válida."}]);const bad=errors(req,res);if(bad)return bad;try{const result=await receivePurchase({businessId:req.business.id,userId:req.session.user.id,purchaseId,items:matchedData(req).items});if(result.error==="not_found")return res.status(404).json({error:{code:"PURCHASE_NOT_FOUND",message:"No se encontró la orden de compra."}});if(result.error==="closed")return domain(res,"PURCHASE_CLOSED","La orden ya fue recibida o cancelada.");if(result.error==="quantity_exceeded")return domain(res,"RECEIPT_QUANTITY_EXCEEDED","La cantidad recibida supera la cantidad pendiente.",422);if(result.error==="item_not_found")return domain(res,"PURCHASE_ITEM_NOT_FOUND","El producto no pertenece a esta orden.",422);return res.json({data:result});}catch(error){return next(error)}}
export async function cancelPurchaseController(req,res,next){const purchaseId=id(req.params.purchaseId);if(!purchaseId)return invalid(res,[{field:"purchaseId",message:"La orden no es válida."}]);try{if(!(await cancelPurchase(req.business.id,purchaseId,req.session.user.id)))return domain(res,"PURCHASE_NOT_CANCELLABLE","La orden no existe o no puede cancelarse.");return res.json({data:{cancelled:true}})}catch(error){return next(error)}}
