import { matchedData, validationResult } from "express-validator";
import { calculateRecipeCost, createRecipe, getRecipe, getRecipeLocations, getRecipeProducts, listRecipes, produceRecipe, updateRecipe, updateRecipeStatus } from "../db/recipeQueries.js";

function id(value) { return /^[1-9]\d*$/.test(String(value)) ? Number(value) : null; }
function validationError(res, errors) { return res.status(400).json({ error: { code: "VALIDATION_ERROR", message: "Revisa los campos enviados.", fields: errors } }); }
function serialize(recipe) { return { id: Number(recipe.id), name: recipe.name, productId: Number(recipe.product_id), productName: recipe.product_name, sku: recipe.sku, yieldQuantity: Number(recipe.yield_quantity), yieldUnit: recipe.yield_unit, wastePercentage: Number(recipe.waste_percentage), manualCost: recipe.manual_cost === null || recipe.manual_cost === undefined ? null : Number(recipe.manual_cost), isEstimated: Boolean(recipe.is_estimated), laborCost: Number(recipe.labor_cost || 0), logisticsCost: Number(recipe.logistics_cost || 0), status: recipe.status, ingredientCount: recipe.ingredient_count === undefined ? undefined : Number(recipe.ingredient_count), updatedAt: recipe.updated_at }; }
function detailResponse(detail) { const recipe = serialize(detail.recipe); return { recipe: { ...recipe, instructions: detail.recipe.instructions, manualCostNotes: detail.recipe.manual_cost_notes }, ingredients: detail.ingredients.map((item) => ({ id: Number(item.id), itemId: Number(item.item_id), itemName: item.item_name, sku: item.sku, quantity: Number(item.quantity), unit: item.unit, currentCost: item.cost_price === null ? null : Number(item.cost_price), ingredientCost: Number(item.cost_price ?? 0) * Number(item.quantity) })), cost: { ingredientCost: Number(detail.cost.ingredientCost.toFixed(2)), wasteCost: Number(detail.cost.wasteCost.toFixed(2)), productionCost: Number(detail.cost.productionCost.toFixed(2)), unitCost: Number(detail.cost.unitCost.toFixed(2)), isEstimated: detail.cost.isEstimated } }; }
function handleErrors(req, res) { const result = validationResult(req); return result.isEmpty() ? null : validationError(res, result.array().map((error) => ({ field: error.path, message: error.msg }))); }

export async function listRecipesController(req, res, next) { try { const recipes = await listRecipes(req.business.id); return res.json({ data: { recipes: recipes.map(serialize) } }); } catch (error) { return next(error); } }
export async function recipeOptions(req, res, next) { try { const [products, locations] = await Promise.all([getRecipeProducts(req.business.id), getRecipeLocations(req.business.id)]); return res.json({ data: { products: products.map((p) => ({ id: Number(p.id), name: p.name, sku: p.sku, costPrice: p.cost_price === null ? null : Number(p.cost_price), stock: Number(p.stock) })), locations: locations.map((location) => ({ id: Number(location.id), name: location.name, code: location.code, isDefault: Boolean(location.is_default) })) } }); } catch (error) { return next(error); } }
export async function getRecipeController(req, res, next) { const recipeId = id(req.params.recipeId); if (!recipeId) return validationError(res, [{ field: "recipeId", message: "La receta no es válida." }]); try { const detail = await getRecipe(req.business.id, recipeId); if (!detail) return res.status(404).json({ error: { code: "RECIPE_NOT_FOUND", message: "No se encontró la receta." } }); return res.json({ data: detailResponse(detail) }); } catch (error) { return next(error); } }
function recipeDomainError(res, error) { return validationError(res, [{ field: "ingredients", message: error.message }]); }
export async function createRecipeController(req, res, next) { const errors = handleErrors(req, res); if (errors) return errors; try { const detail = await createRecipe({ businessId: req.business.id, userId: req.session.user.id, data: matchedData(req) }); return res.status(201).json({ data: detailResponse(detail) }); } catch (error) { if (error.message?.includes("no puede utilizarse a sí misma") || error.message?.includes("dependencia circular")) return recipeDomainError(res, error); return next(error); } }
export async function updateRecipeController(req, res, next) { const recipeId = id(req.params.recipeId); if (!recipeId) return validationError(res, [{ field: "recipeId", message: "La receta no es válida." }]); const errors = handleErrors(req, res); if (errors) return errors; try { const detail = await updateRecipe({ businessId: req.business.id, recipeId, data: matchedData(req) }); if (!detail) return res.status(404).json({ error: { code: "RECIPE_NOT_FOUND", message: "No se encontró la receta activa." } }); return res.json({ data: detailResponse(detail) }); } catch (error) { if (error.message?.includes("no puede utilizarse a sí misma") || error.message?.includes("dependencia circular")) return recipeDomainError(res, error); return next(error); } }
export async function updateRecipeStatusController(req, res, next) { const recipeId = id(req.params.recipeId); if (!recipeId) return validationError(res, [{ field: "recipeId", message: "La receta no es válida." }]); const errors = handleErrors(req, res); if (errors) return errors; try { const recipe = await updateRecipeStatus({ businessId: req.business.id, recipeId, status: matchedData(req).status }); if (!recipe) return res.status(404).json({ error: { code: "RECIPE_NOT_FOUND", message: "No se encontró la receta." } }); return res.json({ data: { recipe: serialize(recipe) } }); } catch (error) { return next(error); } }
export async function produceRecipeController(req, res, next) { const recipeId = id(req.params.recipeId); if (!recipeId) return validationError(res, [{ field: "recipeId", message: "La receta no es válida." }]); const errors = handleErrors(req, res); if (errors) return errors; try { const result = await produceRecipe({ businessId: req.business.id, recipeId, userId: req.session.user.id, ...matchedData(req) }); if (result.error === "not_found") return res.status(404).json({ error: { code: "RECIPE_NOT_FOUND", message: "No se encontró la receta activa." } }); if (result.error === "location_not_found") return validationError(res, [{ field: "locationId", message: "Selecciona una ubicación activa." }]); if (result.error === "insufficient_stock") return res.status(409).json({ error: { code: "INSUFFICIENT_STOCK", message: "No hay existencias suficientes para producir el lote." } }); return res.status(201).json({ data: { production: result } }); } catch (error) { return next(error); } }
