import { getTransaction, getTransactionOptions, listTransactions } from "../db/transactionQueries.js";

const types = new Set(["entry", "exit", "adjustment", "transfer", "sale", "production"]);
const positive = (value) => /^[1-9]\d*$/.test(String(value)) ? Number(value) : null;
const date = (value) => /^\d{4}-\d{2}-\d{2}$/.test(value || "") ? value : null;
function error(res, fields) { return res.status(400).json({ error: { code: "VALIDATION_ERROR", message: "Revisa los filtros enviados.", fields } }); }
function read(req, res) { const q = typeof req.query.q === "string" ? req.query.q.trim().slice(0, 100) : ""; const type = typeof req.query.type === "string" && types.has(req.query.type) ? req.query.type : ""; const dateFrom = req.query.dateFrom ? date(req.query.dateFrom) : null; const dateTo = req.query.dateTo ? date(req.query.dateTo) : null; const locationId = req.query.locationId ? positive(req.query.locationId) : null; const userId = req.query.userId ? positive(req.query.userId) : null; const fields = []; if (req.query.type && !type) fields.push({ field: "type", message: "El tipo no es válido." }); if (req.query.dateFrom && !dateFrom) fields.push({ field: "dateFrom", message: "La fecha inicial no es válida." }); if (req.query.dateTo && !dateTo) fields.push({ field: "dateTo", message: "La fecha final no es válida." }); if (dateFrom && dateTo && dateFrom > dateTo) fields.push({ field: "dateTo", message: "La fecha final debe ser posterior a la inicial." }); if (req.query.locationId && !locationId) fields.push({ field: "locationId", message: "La ubicación no es válida." }); if (req.query.userId && !userId) fields.push({ field: "userId", message: "El usuario no es válido." }); if (fields.length) { error(res, fields); return null; } return { q, type, dateFrom, dateTo, locationId, userId }; }
function serialize(row) { return { id: Number(row.id), date: row.created_at, type: row.transaction_type, reference: row.reference, reason: row.reason, product: { id: Number(row.product_id), name: row.product_name, sku: row.sku }, quantity: Number(row.quantity_delta), cost: row.cost_price === null ? null : Number(row.cost), origin: row.from_location_id ? { id: Number(row.from_location_id), name: row.from_location_name } : null, destination: row.to_location_id ? { id: Number(row.to_location_id), name: row.to_location_name } : null, location: { id: Number(row.location_id), name: row.location_name, code: row.location_code }, user: { id: Number(row.user_id), username: row.username }, status: "completed", previousStock: Number(row.previous_stock), resultingStock: Number(row.resulting_stock) }; }
export async function listTransactionsController(req, res, next) { const params = read(req, res); if (!params) return; const page = positive(req.query.page) ?? 1; const limit = Math.min(positive(req.query.limit) ?? 25, 50); try { const result = await listTransactions({ businessId: req.business.id, ...params, limit, offset: (page - 1) * limit }); const totalPages = Math.ceil(result.count / limit); return res.json({ data: { transactions: result.rows.map(serialize), filters: params, pagination: { page: totalPages ? page : 1, pageSize: limit, totalItems: result.count, totalPages } } }); } catch (e) { return next(e); } }
export async function getTransactionController(req, res, next) { const transactionId = positive(req.params.transactionId); if (!transactionId) return error(res, [{ field: "transactionId", message: "La transacción no es válida." }]); try { const row = await getTransaction({ businessId: req.business.id, transactionId }); if (!row) return res.status(404).json({ error: { code: "TRANSACTION_NOT_FOUND", message: "No se encontró la transacción." } }); return res.json({ data: { transaction: serialize(row) } }); } catch (e) { return next(e); } }
export async function transactionOptions(req, res, next) { try { const options = await getTransactionOptions(req.business.id); return res.json({ data: { locations: options.locations, users: options.users, products: options.products } }); } catch (e) { return next(e); } }
