import { matchedData, validationResult } from "express-validator";
import AppError from "../utils/AppError.js";
import { changeLocationStatus, createLocation, getLocation, listLocations, makeDefaultLocation, updateLocation } from "../db/locationQueries.js";
const id=v=>Number.isInteger(Number(v))&&Number(v)>0?Number(v):null;
const form=(l={})=>({name:l.name??"",code:l.code??"",locationType:l.location_type??"branch",address:l.address??"",phone:l.phone??"",notes:l.notes??""});
export async function showLocations(req,res,next){try{res.render('locations/index',{title:'Ubicaciones',locations:await listLocations(req.business.id)})}catch(e){next(e)}}
export async function showLocation(req,res,next){try{const location=await getLocation(id(req.params.id),req.business.id);if(!location)return next(new AppError('Ubicación no encontrada',404));res.render('locations/details',{title:location.name,location})}catch(e){next(e)}}
export const showNew=(req,res)=>res.render('locations/form',{title:'Nueva ubicación',location:form(),errors:[]});
async function save(req,res,next,editing){const locationId=editing?id(req.params.id):null;const errors=validationResult(req);if(errors.isEmpty()===false)return res.status(400).render('locations/form',{title:editing?'Editar ubicación':'Nueva ubicación',location:form(req.body),locationId,errors:errors.array()});try{const row=editing?await updateLocation(locationId,matchedData(req),req.business.id):await createLocation(matchedData(req),req.business.id);if(!row)return next(new AppError('Ubicación no encontrada',404));res.redirect('/locations/'+row.id)}catch(e){if(e.code==='23505')return res.status(409).render('locations/form',{title:editing?'Editar ubicación':'Nueva ubicación',location:form(req.body),locationId,errors:[{path:'name',msg:'El nombre o código ya existe en este negocio.'}]});next(e)}}
export const addLocation=(req,res,next)=>save(req,res,next,false);export async function showEdit(req,res,next){try{const l=await getLocation(id(req.params.id),req.business.id);if(!l)return next(new AppError('Ubicación no encontrada',404));res.render('locations/form',{title:'Editar ubicación',location:form(l),locationId:l.id,errors:[]})}catch(e){next(e)}};export const editLocation=(req,res,next)=>save(req,res,next,true);
export async function showTransition(req,res,next){try{const location=await getLocation(id(req.params.id),req.business.id);if(!location)return next(new AppError('Ubicación no encontrada',404));res.render('locations/transition',{title:'Ubicación',location,action:req.params.action})}catch(e){next(e)}}
export async function transition(req,res,next){try{const locationId=id(req.params.id), action=req.params.action;let row;if(action==='make-default')row=await makeDefaultLocation(locationId,req.business.id);else row=await changeLocationStatus(locationId,req.business.id,action==='deactivate'?'active':'inactive',action==='deactivate'?'inactive':'active');if(!row)return res.status(409).render('locations/transition',{title:'Ubicación',location:await getLocation(locationId,req.business.id),action,error:'La transición no está permitida.'});res.redirect('/locations/'+locationId)}catch(e){next(e)}}
