import { matchedData, validationResult } from "express-validator";
import AppError from "../utils/AppError.js";
import { changeSupplierStatus, createSupplier, getSupplier, listSuppliers, updateSupplier } from "../db/supplierQueries.js";
const form=(supplier={})=>({name:supplier.name??"",legalName:supplier.legal_name??"",taxId:supplier.tax_id??"",contactName:supplier.contact_name??"",email:supplier.email??"",phone:supplier.phone??"",address:supplier.address??"",notes:supplier.notes??""});
const id=v=>Number.isInteger(Number(v))&&Number(v)>0?Number(v):null;
export async function showSuppliers(req,res,next){try{const status=["active","inactive","all"].includes(req.query.status)?req.query.status:"active",q=typeof req.query.q==="string"?req.query.q.trim().slice(0,100):"",page=/^[1-9]\d*$/.test(req.query.page)?Math.min(Number(req.query.page),100000):1;const result=await listSuppliers({businessId:req.business.id,status,q,limit:20,offset:(page-1)*20});res.render("suppliers/index",{title:"Proveedores",...result,status,q,page,totalPages:Math.max(1,Math.ceil(result.count/20))})}catch(e){next(e)}}
export async function showSupplier(req,res,next){const supplier=await getSupplier(id(req.params.id),req.business.id);if(!supplier)return next(new AppError("Proveedor no encontrado",404));res.render("suppliers/details",{title:supplier.name,supplier})}
export const showNew=(req,res)=>res.render("suppliers/form",{title:"Nuevo proveedor",supplier:form(),errors:[]});
async function save(req,res,next,editing){const supplierId=editing?id(req.params.id):null;if(editing&&!supplierId)return next(new AppError("Proveedor no encontrado",404));const errors=validationResult(req);if(!errors.isEmpty())return res.status(400).render("suppliers/form",{title:editing?"Editar proveedor":"Nuevo proveedor",supplier:form(req.body),errors:errors.array()});try{const data=matchedData(req);const supplier=editing?await updateSupplier(supplierId,data,req.business.id):await createSupplier(data,req.business.id);if(!supplier)return next(new AppError("Proveedor no encontrado",404));res.redirect(`/suppliers/${supplier.id}`)}catch(e){if(e.code==='23505')return res.status(409).render("suppliers/form",{title:editing?"Editar proveedor":"Nuevo proveedor",supplier:form(req.body),errors:[{path:"name",msg:"Ya existe un proveedor con ese nombre."}]});next(e)}}
export const addSupplier=(req,res,next)=>save(req,res,next,false);export async function showEdit(req,res,next){const supplier=await getSupplier(id(req.params.id),req.business.id);if(!supplier)return next(new AppError("Proveedor no encontrado",404));res.render("suppliers/form",{title:"Editar proveedor",supplier:form(supplier),supplierId:supplier.id,errors:[]})};export const editSupplier=(req,res,next)=>save(req,res,next,true);
export async function showStatus(req,res,next){const supplier=await getSupplier(id(req.params.id),req.business.id);const action=req.params.action;if(!supplier||!['deactivate','reactivate'].includes(action))return next(new AppError("Proveedor no encontrado",404));res.render("suppliers/status",{title:"Proveedor",supplier,action})};export async function setStatus(req,res,next){const action=req.params.action, supplierId=id(req.params.id),from=action==='deactivate'?'active':'inactive',to=action==='deactivate'?'inactive':'active';if(!supplierId||!['deactivate','reactivate'].includes(action))return next(new AppError("Proveedor no encontrado",404));const s=await changeSupplierStatus(supplierId,req.business.id,from,to);if(!s)return next(new AppError("Proveedor no encontrado",404));res.redirect(`/suppliers/${supplierId}`)}
