import pool from "./pool.js";
import { randomUUID } from "node:crypto";
import { auditService } from "../services/auditService.js";

const customerFields = "c.id,c.name,c.phone,c.email,c.address,c.notes,c.status,c.created_at,c.updated_at,u.username AS created_by_username";
export async function listCustomers(businessId, q = "") { const r = await pool.query(`SELECT ${customerFields}, COALESCE(SUM(CASE WHEN ch.status <> 'cancelled' THEN ch.amount ELSE 0 END),0) - COALESCE(SUM(CASE WHEN p.status='active' THEN p.amount ELSE 0 END),0) AS balance FROM customers c LEFT JOIN users u ON u.id=c.created_by LEFT JOIN customer_charges ch ON ch.business_id=c.business_id AND ch.customer_id=c.id LEFT JOIN customer_payments p ON p.business_id=c.business_id AND p.customer_id=c.id WHERE c.business_id=$1 AND ($2='' OR c.name ILIKE $3 OR c.phone ILIKE $3 OR c.email ILIKE $3) GROUP BY c.id,u.username ORDER BY LOWER(c.name),c.id`, [businessId,q,`%${q}%`]); return r.rows; }
export async function getCustomer(businessId, id) { const r=await pool.query(`SELECT ${customerFields}, (SELECT COALESCE(SUM(amount),0) FROM customer_charges WHERE business_id=c.business_id AND customer_id=c.id AND status <> 'cancelled') - (SELECT COALESCE(SUM(amount),0) FROM customer_payments WHERE business_id=c.business_id AND customer_id=c.id AND status='active') AS balance FROM customers c LEFT JOIN users u ON u.id=c.created_by WHERE c.business_id=$1 AND c.id=$2`,[businessId,id]); return r.rows[0] ?? null; }
export async function createCustomer({ businessId, createdBy, name, phone, email, address, notes }) { const r=await pool.query("INSERT INTO customers(business_id,created_by,name,phone,email,address,notes) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *",[businessId,createdBy,name,phone||null,email||null,address||null,notes||null]); return r.rows[0]; }
export async function updateCustomer({ businessId,id,name,phone,email,address,notes }) { const r=await pool.query("UPDATE customers SET name=$1,phone=$2,email=$3,address=$4,notes=$5,updated_at=CURRENT_TIMESTAMP WHERE business_id=$6 AND id=$7 RETURNING *",[name,phone||null,email||null,address||null,notes||null,businessId,id]); return r.rows[0]??null; }
export async function setCustomerStatus(businessId,id,status) { const r=await pool.query("UPDATE customers SET status=$1,updated_at=CURRENT_TIMESTAMP WHERE business_id=$2 AND id=$3 RETURNING *",[status,businessId,id]); return r.rows[0]??null; }
export async function listCharges(businessId, customerId) { const r=await pool.query("SELECT ch.*, COALESCE((SELECT SUM(amount) FROM customer_payments p WHERE p.business_id=ch.business_id AND p.charge_id=ch.id AND p.status='active'),0) paid FROM customer_charges ch WHERE ch.business_id=$1 AND ($2::int IS NULL OR ch.customer_id=$2) ORDER BY ch.due_date DESC,ch.id DESC",[businessId,customerId??null]); return r.rows; }
export async function createCharge(x) { const r=await pool.query("INSERT INTO customer_charges(business_id,customer_id,concept,amount,frequency,due_date,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *",[x.businessId,x.customerId,x.concept,x.amount,x.frequency,x.dueDate,x.notes||null,x.createdBy]); return r.rows[0]; }
export async function getCharge(businessId,id) { const r=await pool.query("SELECT ch.*, COALESCE((SELECT SUM(amount) FROM customer_payments p WHERE p.business_id=ch.business_id AND p.charge_id=ch.id AND p.status='active'),0) paid FROM customer_charges ch WHERE ch.business_id=$1 AND ch.id=$2",[businessId,id]); return r.rows[0]??null; }
export async function updateCharge({businessId,id,concept,amount,frequency,dueDate,notes}) { const r=await pool.query("UPDATE customer_charges SET concept=$1,amount=$2,frequency=$3,due_date=$4,notes=$5,updated_at=CURRENT_TIMESTAMP WHERE business_id=$6 AND id=$7 AND status <> 'cancelled' RETURNING *",[concept,amount,frequency,dueDate,notes||null,businessId,id]); return r.rows[0]??null; }
export async function updateChargeStatus(businessId,id,status) { const r=await pool.query("UPDATE customer_charges SET status=$1,updated_at=CURRENT_TIMESTAMP WHERE business_id=$2 AND id=$3 RETURNING *",[status,businessId,id]); return r.rows[0]??null; }
export async function listPayments(businessId, customerId) { const r=await pool.query("SELECT p.*,c.name AS customer_name,ch.concept,u.username AS created_by_username FROM customer_payments p JOIN customers c ON c.business_id=p.business_id AND c.id=p.customer_id JOIN users u ON u.id=p.created_by LEFT JOIN customer_charges ch ON ch.business_id=p.business_id AND ch.id=p.charge_id WHERE p.business_id=$1 AND ($2::int IS NULL OR p.customer_id=$2) ORDER BY p.paid_at DESC,p.id DESC",[businessId,customerId??null]); return r.rows; }
export async function getPayment(businessId,id) { const r=await pool.query("SELECT p.*,c.name AS customer_name,ch.concept,u.username AS created_by_username FROM customer_payments p JOIN customers c ON c.business_id=p.business_id AND c.id=p.customer_id JOIN users u ON u.id=p.created_by LEFT JOIN customer_charges ch ON ch.business_id=p.business_id AND ch.id=p.charge_id WHERE p.business_id=$1 AND p.id=$2",[businessId,id]); return r.rows[0]??null; }
export async function createPayment(x) { const client=await pool.connect(); try { await client.query("BEGIN"); const customer=await client.query("SELECT id FROM customers WHERE business_id=$1 AND id=$2 FOR UPDATE",[x.businessId,x.customerId]); if(!customer.rowCount) throw Object.assign(new Error("Cliente no encontrado."),{statusCode:404}); const charge=x.chargeId ? await client.query("SELECT id,amount,status,COALESCE((SELECT SUM(amount) FROM customer_payments WHERE business_id=$1 AND charge_id=$2 AND status='active'),0) paid FROM customer_charges WHERE business_id=$1 AND id=$2 AND customer_id=$3 FOR UPDATE",[x.businessId,x.chargeId,x.customerId]) : null; const previous=charge?.rows[0] ? Number(charge.rows[0].amount)-Number(charge.rows[0].paid) : Number((await client.query("SELECT COALESCE(SUM(amount),0) total FROM customer_charges WHERE business_id=$1 AND customer_id=$2 AND status <> 'cancelled'",[x.businessId,x.customerId])).rows[0].total)-Number((await client.query("SELECT COALESCE(SUM(amount),0) total FROM customer_payments WHERE business_id=$1 AND customer_id=$2 AND status='active'",[x.businessId,x.customerId])).rows[0].total); if(charge && !charge.rowCount) throw Object.assign(new Error("Cargo no encontrado."),{statusCode:404}); if(Number(x.amount)>previous) throw Object.assign(new Error("El abono supera el saldo pendiente."),{statusCode:409}); const remaining=previous-Number(x.amount); const folio=`P-${Date.now()}-${randomUUID().slice(0,8)}`; const p=await client.query("INSERT INTO customer_payments(business_id,customer_id,charge_id,folio,amount,payment_method,previous_balance,remaining_balance,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *",[x.businessId,x.customerId,x.chargeId||null,folio,x.amount,x.paymentMethod,previous,remaining,x.notes||null,x.createdBy]); if(charge) await client.query("UPDATE customer_charges SET status=$1,updated_at=CURRENT_TIMESTAMP WHERE business_id=$2 AND id=$3",[remaining===0?"paid":"partially_paid",x.businessId,x.chargeId]); await auditService.record({client,businessId:x.businessId,userId:x.createdBy,module:"collections",action:"register_payment",reference:folio,description:"Pago de cobranza registrado",newValues:{paymentId:p.rows[0].id,customerId:x.customerId,amount:x.amount,remainingBalance:remaining}}); await client.query("COMMIT"); return p.rows[0]; } catch(e) { await client.query("ROLLBACK"); throw e; } finally { client.release(); } }
export async function cancelPayment({businessId,id,userId,reason}) { const client=await pool.connect(); try { await client.query("BEGIN"); const r=await client.query("UPDATE customer_payments SET status='cancelled',cancelled_at=CURRENT_TIMESTAMP,cancelled_by=$1,cancellation_reason=$2 WHERE business_id=$3 AND id=$4 AND status='active' RETURNING *",[userId,reason,businessId,id]); if(!r.rows[0]) { await client.query("ROLLBACK"); return null; } await auditService.record({client,businessId,userId,module:"collections",action:"cancel",reference:r.rows[0].folio,description:"Pago de cobranza cancelado",previousValues:{status:"active"},newValues:{status:"cancelled",reason}}); await client.query("COMMIT"); return r.rows[0]; } catch(e) { await client.query("ROLLBACK").catch(()=>{}); throw e; } finally { client.release(); } }
export async function summary(businessId) { const r=await pool.query("SELECT (SELECT COUNT(*) FROM customers WHERE business_id=$1 AND status='active') active_customers,(SELECT COALESCE(SUM(amount),0) FROM customer_charges WHERE business_id=$1 AND status <> 'cancelled') total_charges,(SELECT COALESCE(SUM(amount),0) FROM customer_payments WHERE business_id=$1 AND status='active') paid_total,(SELECT COUNT(DISTINCT customer_id) FROM customer_charges WHERE business_id=$1 AND status='overdue') overdue_accounts",[businessId]); return r.rows[0]; }
export async function listCollectionAlerts(businessId) { const r=await pool.query("SELECT ch.id AS charge_id,ch.customer_id,c.name AS customer_name,ch.concept,ch.amount,ch.due_date,(ch.due_date - CURRENT_DATE) AS days_until_due,COALESCE(SUM(p.amount) FILTER (WHERE p.status='active'),0) AS paid FROM customer_charges ch JOIN customers c ON c.business_id=ch.business_id AND c.id=ch.customer_id LEFT JOIN customer_payments p ON p.business_id=ch.business_id AND p.charge_id=ch.id WHERE ch.business_id=$1 AND ch.frequency='monthly' AND ch.status <> 'cancelled' AND ch.due_date <= CURRENT_DATE + 7 GROUP BY ch.id,c.name HAVING ch.amount > COALESCE(SUM(p.amount) FILTER (WHERE p.status='active'),0) ORDER BY ch.due_date",[businessId]); return r.rows; }
