import { Info } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "./Button.jsx";
import { Card } from "./Card.jsx";

const content = {
  dashboard: ["El dashboard resume el periodo seleccionado.", ["Ventas: total vendido y operaciones.", "Utilidad: ventas menos costos; puede ser estimada.", "Inventario: valor, unidades y alertas.", "Cobranza: saldos pendientes y vencidos.", "Gastos: costos registrados.", "Alertas: situaciones que requieren atención."]],
  breakEven: ["El punto de equilibrio indica cuánto necesitas vender para cubrir costos.", ["Costos fijos: permanecen aunque no haya ventas.", "Costos variables: cambian con los productos vendidos.", "Fórmula: costos fijos ÷ margen de contribución por unidad."], "El resultado es una estimación basada en los datos registrados."],
  costs: ["Registra los gastos que ayudan a operar el negocio.", ["Fijos: no dependen directamente de las ventas.", "Variables: cambian según la actividad.", "Mano de obra y logística: trabajo, transporte y preparación.", "Periodicidad: semanal, mensual, anual o única."], "Solo se incluyen gastos activos y vigentes."],
  recipes: ["Una receta relaciona un producto final con sus ingredientes.", ["Ingredientes y cantidades: deben corresponder al rendimiento.", "Merma: desperdicio esperado.", "Costo unitario: costo total del lote ÷ rendimiento.", "Producción: descuenta ingredientes y aumenta el producto final."], "Los ingredientes deben tener costos registrados."],
  collections: ["Registra clientes, cargos y pagos para mantener estados de cuenta claros.", ["Clientes: personas o negocios a los que se cobra.", "Cargos: importes pendientes, incluidos los mensuales.", "Pagos: abonos que reducen el saldo.", "Vencimientos: identifican pagos próximos o atrasados."], "El ticket del pago puede abrirse e imprimirse."],
  purchases: ["El flujo es: orden de compra → recepción parcial o total → aumento de inventario → transacción.", ["Recepción parcial: registra solo lo que llegó.", "Recepción total: completa las cantidades pendientes.", "Stock: cada recepción aumenta existencias."], "La cantidad recibida no puede superar la solicitada ni duplicarse."],
  returns: ["Las devoluciones y pérdidas documentan salidas justificadas de inventario.", ["Devolución a proveedor: devuelve productos de una orden recibida; no puede superar lo recibido.", "Mercancía dañada: registra daño, caducidad, destrucción o pérdida y descuenta unidades.", "Efecto: disminuye el stock y crea una transacción histórica.", "Cancelación: revierte el movimiento y devuelve unidades cuando corresponde.", "Diferencias: devolución vuelve al proveedor; daño queda inutilizable; pérdida ya no está disponible.", "Recomendación: registra el motivo y la cantidad exacta."], "Ejemplo: si recibiste 20 piezas y 2 llegaron dañadas, registra 2. El inventario queda en 18 y aparece en Transacciones."],
  alerts: ["Las alertas comparan el stock con los límites configurados.", ["Agotado: stock cero.", "Stock bajo: está en o por debajo del mínimo.", "Stock excedente: supera el máximo.", "Mínimo y máximo: límites esperados por ubicación.", "Cantidad sugerida: unidades para llegar al máximo."], "Los colores indican urgencia, revisión y estado normal."],
  transactions: ["Es el historial unificado de cambios en el inventario.", ["Entrada: aumenta existencias.", "Salida: descuenta productos.", "Ajuste: corrige diferencias.", "Transferencia: mueve stock entre ubicaciones.", "Venta y producción: registran consumos y aumentos relacionados."], "Usa filtros por producto, tipo, fecha, ubicación y usuario; las referencias automáticas facilitan el seguimiento."],
  reports: ["Los reportes ayudan a analizar inventario y actividad.", ["Inventario actual: existencias, costos y valor.", "Movimientos: operaciones realizadas.", "Sin movimiento: productos sin actividad reciente.", "Stock bajo: diferencia contra el mínimo."], "Filtra por fechas, producto, categoría, ubicación o usuario y exporta CSV, Excel o impresión."],
  inventory: ["Consulta las existencias por producto y ubicación.", ["Usa búsqueda y filtros para encontrar productos.", "Revisa mínimos y máximos antes de reabastecer.", "El stock se actualiza mediante operaciones de inventario."]]
};
function keyFor(moduleKey, businessId) { return `help_info_${moduleKey}_${businessId || "global"}`; }
export function HelpInfoPanel({ moduleKey, businessId }) { const data=content[moduleKey]; const key=keyFor(moduleKey,businessId); const [hidden,setHidden]=useState(()=>localStorage.getItem(key)==="hidden"); const [expanded,setExpanded]=useState(true); useEffect(()=>{const reset=()=>{localStorage.removeItem(key);setHidden(false);setExpanded(true)};window.addEventListener("help-info:reset",reset);return()=>window.removeEventListener("help-info:reset",reset)},[key]); if(!data)return null; if(hidden)return <div className="help-info-panel__restore"><Button type="button" variant="secondary" onClick={()=>{localStorage.removeItem(key);setHidden(false)}}>Mostrar explicación</Button></div>; return <Card className="help-info-panel"><header className="help-info-panel__header"><div className="help-info-panel__title"><Info aria-hidden="true"/><h2>{moduleKey==="returns"?"¿Cómo funcionan las devoluciones y las pérdidas?":"¿Cómo funciona?"}</h2></div><Button type="button" variant="secondary" aria-expanded={expanded} aria-controls={`help-${moduleKey}`} onClick={()=>setExpanded(x=>!x)}>{expanded?"Ocultar explicación":"Mostrar explicación"}</Button></header>{expanded&&<div id={`help-${moduleKey}`} className="help-info-panel__content"><p>{data[0]}</p><ul>{data[1].map((item)=><li key={item}>{item}</li>)}</ul>{data[2]&&<p className={moduleKey==="returns"?"help-info-panel__example":""}>{data[2]}</p>}<button type="button" className="help-info-panel__never" onClick={()=>{localStorage.setItem(key,"hidden");setHidden(true)}}>No volver a mostrar</button></div>}</Card>; }
export function resetHelpInfoPanels() { Object.keys(localStorage).filter((key)=>key.startsWith("help_info_")).forEach((key)=>localStorage.removeItem(key)); window.dispatchEvent(new Event("help-info:reset")); }
